services:
  app:
    volumes:
      - ./config/host/20-xdebug.ini:/etc/php/8.2/apache2/conf.d/20-xdebug.ini

  db:
    volumes:
      - data:/var/lib/mysql
    ports:
      - $DB_PORT:3306
volumes:
  data:
