#!/bin/bash
set -ex

# Get the release name using git
RELEASE_NAME=$(git describe --always)

# Extract the release body from CHANGELOG.md
RELEASE_BODY=$(awk 'BEGIN {found=0} /^## / {if (found) exit; found=1} found {print}' CHANGELOG.md)

# Create the JSON payload
JSON_DATA=$(cat << EOF
{
  "tag_name": "${RELEASE_NAME}",
  "name": "Release ${RELEASE_NAME}",
  "body": $(echo "$RELEASE_BODY" | jq -Rs .),
  "draft": false,
  "prerelease": false
}
EOF
)

# Make the API call
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
  -d "$JSON_DATA"
