#!/bin/bash
source ~/.secrets
set -ex

VERSION=`git describe --always`
export VERSION

j2 .env.j2 > .env
compose="docker compose -p cords-parnter-portal-backend-builder"
$compose run -u $(id -u) app composer install
$compose run -u $(id -u) app composer dump-env prod

rsync \
  -a . \
  --exclude=/docker-compose.override.yml \
  --exclude=/var \
  --exclude=/data \
  --delete \
  $1

cd $1
docker compose up -d
docker compose exec -T -u $(id -u) app ./bin/console doctrine:migrations:migrate
docker compose exec -T -u $(id -u) app ./bin/console cache:clear
sudo chmod -R 777 var
