#!/bin/bash
set -e

source ~/.secrets

echo "::add-mask::$APP_SECRET"
echo "::add-mask::$SYSTEM_TOKEN"
echo "::add-mask::$SENDGRID_KEY"

export COMPOSE_FILE=docker-compose.yml:docker-compose.db.yml:docker-compose.letsencrypt.yml
export TRAEFIK_HOSTNAME=partners-api.cords.dev
export CLIENT_HOSTNAME=partners.cords.dev
export APP_ENV=prod
export COOKIE_DOMAIN=.cords.dev
export DATABASE_URL="mysql://root@$COMPOSE_PROJECT_NAME-db:3306/partners?serverVersion=8.0&charset=utf8mb4"
export CORS_ALLOW_ORIGIN=.*.cords.dev
export FIREBASE_SERVICE_URL=http://cords-firebase-service-$ENV_NAME:3000
export SENTRY_DSN=https://24ddf8367cdabdf6efa403dce1dfa187@o4504168857927680.ingest.us.sentry.io/4507124314734592
export ADMIN_EMAIL=accounts@cords.ai
export CORDS_ADMIN_FRONTEND_URL=admin.cords.dev
export FROM_EMAIL="Accounts | CORDS <communications@cords.ai>"
export ENFORCE_PROD_RESTRICTIONS=TRUE
export WHITELISTED_URL=cords-widget.pages.dev
